spring:
  profiles: default

datasource:
  bms:
    initialize: true
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/test"
    user-name: "daisy"
    password: "daisy!"
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

bms-meta:
  common:
    type: type
    key: key
    value: value
    path: path
    file-pattern: filePattern
    path-attribute: pathAttributes
    scan-range: scanRange
    date-pattern: datePattern
    date: date
    text-encoding: textEncoding
  execute:
    default-execute-group: LIMIT
  file-info:
    res-sche-path: /Users/devjackie/ara-bms/bms/sche/
    res-sche-filename-1: bms_sche_2018042802_24.dat
    res-sche-filename-2: bms_sche_2018042900_02.dat

# sample test
name: prod-YAML
environment: production
servers:
    - www.abc.com
    - www.xyz.com