# http://smasue.github.io/spring-yml-datasources
spring:
  profiles.active: local
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration

--- # local
spring:
  profiles: local

datasource:
  bms:
    initialize: true
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/test"
    user-name: "daisy"
    password: "daisy!"
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

bms-meta:
  common:
    type: type
    key: key
    value: value
    path: path
    file-pattern: filePattern
    path-attribute: pathAttributes
    scan-range: scanRange
    date-pattern: datePattern
    date: date
    text-encoding: textEncoding
  execute:
    default-execute-group: LIMIT
  file-info:
    res-sche-yaml-path: linkServer/BMS/BMS_DD_AD_RES_SCHE_LOCAL.yml
    res-sche-path: /Users/devjackie/ara-bms/bms/sche/
    res-sche-filename-pre: bms_sche_
    res-sche-filename-suf-1: _02-24.DAT
    res-sche-filename-suf-2: _00-02.DAT
    res-sche-fin-path: /Users/devjackie/ara-bms/bms/sche/
    res-sche-fin-filename-suf-1: _02-24.FIN
    res-sche-fin-filename-suf-2: _00-02.FIN
  zookeeper-info:
    bms-sche-step1-uri: /bms/RES_SCHE/STEP1
    bms-sche-step2-uri: /bms/RES_SCHE/STEP2


--- # develop
spring:
  profiles: develop

datasource:
  bms:
    initialize: true
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://14.63.172.240:5432/ara"
    user-name: "daisyara"
    password: "daisyara!"
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

bms-meta:
  common:
    type: type
    key: key
    value: value
    path: path
    file-pattern: filePattern
    path-attribute: pathAttributes
    scan-range: scanRange
    date-pattern: datePattern
    date: date
    text-encoding: textEncoding
  execute:
    default-execute-group: LIMIT
  file-info:
    res-sche-yaml-path: linkServer/BMS/BMS_DD_AD_RES_SCHE_DEVELOP.yml
    res-sche-path: /data/ara-bms/bms/sche/
    res-sche-filename-pre: bms_sche_
    res-sche-filename-suf-1: _02-24.DAT
    res-sche-filename-suf-2: _00-02.DAT
    res-sche-fin-path: /data/ara-bms/bms/sche/
    res-sche-fin-filename-suf-1: _02-24.FIN
    res-sche-fin-filename-suf-2: _00-02.FIN
  zookeeper-info:
    bms-sche-step1-uri: /bms/RES_SCHE/STEP1
    bms-sche-step2-uri: /bms/RES_SCHE/STEP2


--- # production
spring:
  profiles: production

datasource:
  bms:
    initialize: true
    driver-class-name: "org.postgresql.Driver"
    url: "jdbc:postgresql://daisy-ara01:5444/ara"
    user-name: "daisyara"
    password: "daisyara!"
    initial-size: 10
    max-active: 10
    max-idle: 10
    min-idle: 10
    max-wait: 3000

bms-meta:
  common:
    type: type
    key: key
    value: value
    path: path
    file-pattern: filePattern
    path-attribute: pathAttributes
    scan-range: scanRange
    date-pattern: datePattern
    date: date
    text-encoding: textEncoding
  execute:
    default-execute-group: LIMIT
  file-info:
    res-sche-yaml-path: linkServer/BMS/BMS_DD_AD_RES_SCHE.yml
    res-sche-path: /data/ara-bms/bms/sche/
    res-sche-filename-pre: bms_sche_
    res-sche-filename-suf-1: _02-24.DAT
    res-sche-filename-suf-2: _00-02.DAT
    res-sche-fin-path: /data/ara-bms/bms/sche/
    res-sche-fin-filename-suf-1: _02-24.FIN
    res-sche-fin-filename-suf-2: _00-02.FIN
  zookeeper-info:
    bms-sche-step1-uri: /bms/RES_SCHE/STEP1
    bms-sche-step2-uri: /bms/RES_SCHE/STEP2
